# Generated by Django 2.2.24 on 2021-09-04 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 0, 54, 20, 292092, tzinfo=utc)),
        ),
    ]
