# Generated by Django 2.2.24 on 2021-09-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_auto_20210904_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created_date',
        ),
    ]
