# Generated by Django 2.2.24 on 2021-09-09 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0007_auto_20210909_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 7, 15, 33, 178496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 7, 15, 33, 177977, tzinfo=utc)),
        ),
    ]
