# Generated by Django 2.2.24 on 2021-09-27 00:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0011_auto_20210924_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 27, 0, 52, 9, 252168, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
